// app/layout.js or app/layout.tsx

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@components/LayoutWrapper";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Server-side metadata export
export const metadata = {
  title: {
    template: '%s | Blue Ocean',
    default: 'Blue Ocean',
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <ToastContainer position="top-center" autoClose={3000} />
       <LayoutWrapper>{children}</LayoutWrapper> 
      </body>
    </html>
  );
}
